apiVersion: v1
kind: Pod
metadata:
  name: credspod
  namespace: zenspace1
spec:
  containers:
  - name: credentials
    image: alpine
    command: ["sh", "-c", "echo 'developer\ndevpass123' > /zencorp/creds.txt && sleep 2400"] # 40 minutes (40 mins * 60 secs)
    volumeMounts:
    - name: zencorp-volume
      mountPath: /zencorp
  volumes:
  - name: zencorp-volume
    hostPath:
      path: /zencorp
