apiVersion: v1
kind: Pod
metadata:
  name: multipod
  namespace: zenspace3
spec:
  containers:
  - name: nginx-container
    image: nginx
  - name: alpine-container
    image: alpine
    command: ["tail", "-f", "/dev/null"]
