apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zencorpod
  namespace: zenspace2
spec:
  replicas: 17
  serviceName: zencorpod-0
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: hello-world
