apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zencorpod
  namespace: zenspace3
spec:
  replicas: 17
  serviceName: my-statefulset
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx:latest
